parameters:
    classname: VideogameBundle:Videogame

services:
    linok_videogame.Videogamehandler:
        class: Linok\VideogameBundle\Videogamehandler\Videogamehandler
        arguments: [@doctrine.orm.entity_manager, %classname%]
