parameters:
    linok_videogame.entity.videogame.class: VideogameBundle:Videogame

services:
    linok_videogame.videogame_handler:
        class: Linok\VideogameBundle\Videogamehandler\Videogamehandler
        arguments: [@doctrine.orm.entity_manager, %linok_videogame.entity.videogame.class%]
