<?php

namespace Linok\VideogameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideogameRepository extends EntityRepository
{
}
